fluent-bit:
  kind: DaemonSet

  resources: {}
  #   limits:
  #     cpu: 100m
  #     memory: 128Mi
  #   requests:
  #     cpu: 100m
  #     memory: 128Mi

  flush: 1

  logLevel: info

  metricsPort: 2020

  luaScripts: {}

  ## https://docs.fluentbit.io/manual/administration/configuring-fluent-bit/classic-mode/configuration-file
  config:
    service: |
      [SERVICE]
          Daemon Off
          Flush {{ .Values.flush }}
          Log_Level {{ .Values.logLevel }}
          Parsers_File /fluent-bit/etc/parsers.conf
          Parsers_File /fluent-bit/etc/conf/custom_parsers.conf
          HTTP_Server On
          HTTP_Listen 0.0.0.0
          HTTP_Port {{ .Values.metricsPort }}
          Health_Check On

    ## https://docs.fluentbit.io/manual/pipeline/inputs
    inputs: |
      [INPUT]
          Name tail
          Path /var/log/containers/*.log
          multiline.parser docker, cri
          Tag kube.*
          Mem_Buf_Limit 5MB
          Skip_Long_Lines On

    ## https://docs.fluentbit.io/manual/pipeline/filters
    filters: |
      [FILTER]
          Name kubernetes
          Match kube.*
          Merge_Log On
          Keep_Log Off
          K8S-Logging.Parser On
          K8S-Logging.Exclude On
          Kube_URL https://kubernetes.default.svc.cluster.local:443

      # [FILTER]
      #     Name nest
      #     Match *
      #     Operation lift
      #     Nested_under kubernetes
      #     Add_prefix kubernetes_

    ## https://docs.fluentbit.io/manual/pipeline/outputs
    outputs: |
      [OUTPUT]
          Name es
          Match kube.*
          Host elasticsearch.argocd.svc.cluster.local
          Port 9200
          Retry_Limit False
          Suppress_Type_Name On
          Logstash_Format On
          Logstash_Prefix namespace_name
          Logstash_Prefix_Key $kubernetes['namespace_name']
          # Logstash_Prefix_Key kubernetes_pod_name
          # Logstash_Prefix_Key $kubernetes['namespace_name']
          # Index test

    ## https://docs.fluentbit.io/manual/pipeline/parsers
    customParsers: |
      [PARSER]
          Name docker_no_time
          Format json
          Time_Keep Off
          Time_Key time
          Time_Format %Y-%m-%dT%H:%M:%S.%L
